### ISSUE TITLE
acceptSecContext

### ISSUE THREAD

**Issue by norrad** [cconlon/kerberos-android-ndk#6]
I have a test server application from Oracle.

I use the kerberos-android-ndk to run against it.

The Oracle application has a test client, that set the context as below.

GSSContext context = manager.createContext(serverName,
					krb5Oid,
					null,
                                                                                     GSSContext.DEFAULT_LIFETIME);
The Oracle client handles this fine.

The NDK client throws an exception because the client credentials are passed as a null.

If I pass the client credentials, into the createContext and pass null for the OID, the NDK application is happy, but the server Oracle application on a acceptSecContext throws an exception declaring 

No valid credentials provided
Failed to find any kerberos credentials

**Comment by cconlon** [comment]
Haven't heard back in a while, closing for now.
