### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by Jellygoose** [cconlon/kerberos-android-ndk#9]
Hello,

I'm a bit confused about the license of the code in this project.

The way I interpret the readme and the headers of the files, the GPL license applies to the wolfSSL crypto library and the MIT/BSD licenses applies to the kerberos parts and can be found on the headers of the kerberos code. Does this mean I can use some of the modifications you did to the kerberos sources and keep the MIT license on this or did you intend for those modifications to also be under GPL?

I don't want to breach any licenses :)

Thanks in advance,
Max

**Comment by cconlon** [comment]
Hi,

Your understanding is correct.  The changes made to the Kerberos code were submitted back to MIT under their own license.

Thanks,
Chris
